### ISSUE TITLE
可以支持电驴协议吗？

### ISSUE THREAD

**Issue by bajins** [chinsyo/delink#2]
如 

```
ed2k://|file|yxqy.1080p.BD%E4%B8%AD%E8%8B%B1%E5%8F%8C%E5%AD%97[66%E5%BD%B1%E8%A7%86www.66ys.tv].mp4|3647096208|D33DADCC63E9B555A5D761512AAD61C5|h=6DZTPJXKIZJLRCHDUVPJNAXL7TJARYLW|/
```

**Comment by chinsyo** [comment]
> 如
> 
> ```
> ed2k://|file|yxqy.1080p.BD%E4%B8%AD%E8%8B%B1%E5%8F%8C%E5%AD%97[66%E5%BD%B1%E8%A7%86www.66ys.tv].mp4|3647096208|D33DADCC63E9B555A5D761512AAD61C5|h=6DZTPJXKIZJLRCHDUVPJNAXL7TJARYLW|/
> ```

传输协议不同，暂时没有支持计划。
